spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  resources:
    static-locations: classpath:/static/
  freemarker:
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
wechat:
  appID: wx8765c90ba0291e7c
  appsecret: ca4c7df7375b414cadadf1ba654s554bb
alipay:
  appId: 2016092300579908
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCkwoVtNBSpWcACCNUmEO4nW8Jtv6hlUbldYbWwmr3BLd0H3nroBIZKerUtkCfx1pWv0jlKPfRfL/cJI10kblkYWCVm+SoBnb8Nvp5Cr57KTG7EXRm5bsTYhgDvIaOblwEWHGULzfJvzeoYOL69qIRMzVEpvX+wDfcaOi+66aSNc8bjF1lrDsn9/HJjIO7RS71RYSv29P/NeqCAiNY/z3j7o375ixIDFLbNllX9fB7TzK7rDuDy5FkGnyJ1IQAPRZVOlsRpZqNpD+8trbb02Tj6ghcbyFrLu40/MPC4ygppzw+DMQnsnB2EuS2M/WVYvgm5PpQc0mKTd8jZj/T7MJK7AgMBAAECggEBAKKZCh50iHN9DF21o802ZiHXj7DJtYGQPpQmyq0oeV39SiXq7XauiG1WXhlCK/miIQVsPXfEXrfV2UFechxy/mBlFTxjZ45CxHrnBL6hHN9ewO3vR2TWKVPaI2/bzd/ODZdpnFsi+0BVgdI3ph38Adzdv1ynFC2GCrgKdnJLBEdHQ0OmIbrDc0Qx3evB/OUcA3+ysdr7SY0XBFV3ClPU8fMEytdac8F0tl5BPnuHL6KEeO+mcEP4xoSTFZOwf0ca7/Fazn668RLciJjBfmSA7vkL9zEJD5hflwEG2ftreDQCCahJcdkMTii6jTY5uFISRP9jMGB6mRC8RqaR9aLj32ECgYEA6isgrhUMreZpzxjqGlVfZYbTB8r2/IRBco21dmx88mhDODMxlNWhX9PHOmozLXSDs17QspJq6UKILMzHfH7agaVpBhPFu/QdeK72+zZqctMKOqDZox0jr89A/9nqBSGdBwF244SPsISSbHsU7BVh/fUobhhmzS0a3eCJ9I0sOjECgYEAtB7TbLHsWQpwb2iAjTOj5BKNiJQ6oin0sbmDsasSMOwA6/R163edu2XN3q8x7PnUcg7Gzui5lIIGruQfAEI5fDWyf/G+Tk9DaKX2VwZ6MPz3TuLRC3xcH5lS9RvTFT9J5/IlQ7DRcuXn+nzLMXeo8r10to/ELiOKWw1BRx9f9KsCgYBE0T/daRo80QYvcqb57jUG5USHecJ0G3oQbEzz7JYbt0Bp98GOd+ng+6AFLsizhxZdVHQIxrbcrkzOva+yiqU0jKP8wTrPLcKrgN/cm/VUoWjUKglLwniGZmY3ypbXwzUepfOGkaKYwZ02fEV9zBrsQ2wKTumHSsYmhqKEWCizQQKBgQCcLeZxZ01iX5TiZSCiTtabGiMy/CRjHDIaMJuqYIVjeh/KeKwOwic4qKt7nTmTG4VEaN+l5VGVHbGh0Be5Z7LkqsLeAcVbrYrroIwbJXiqJY5jDnTomqpek9nEwp2i3L++qM37BcR29jbRkYe2muUZpYEgE0SuJQ8AqFujyeawBQKBgQDYKOdg0CSOlcZydM1iu1EvNVBrSYwolx+Rol109iyUp3OQsQlyOX4A+vH6P7edr84IsTvNIHUdqHdDg4pr/o/oc+YECPGUJeIfRCL5IZ36Cc1NiyEjMHIQh5U4W6vbYLPooQ0v9jzqJOu5XhZHyWSPz1wVuDrUbMiV6Y2xjcjQ9g==
  aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoh2tJjgMFl6BKo8XjsTB+rP9vnMfBlB+mS+8ixarf6c38zXiHCvPfb8OIAXTayYEJ53er6Urk9BymZ1MRrioYnk9wOjKGrsW366D934bTqi96qk5Qxreas4mW0ksqVSWWjVvJ104ODfMXsp+dhXcH/fAHcdOZbdnrcoBImtvt/tMI1h057BWi3IyJEB/UCUOnWON2RJYhPYNiBz76sALzi8R7h2dBov91nxZcqYeKs90euW1Pdd/E0LhsWAGOqBSYg+I7czxbN6bHDMumuztHP9odx2T/Z6+wiIgSZ1DJf8/ehVjD6zFlJGfBfDZwMHWBB+knlvbd3PsdMcTM96RLwIDAQAB
  charset: utf-8
  returnUrl: 1
  notifyUrl: 1
mybatis:
  mapper-locations: classpath*:mapper/*.xml